Added methods for downloading the sediment data and converting to shp/tifs
noaa-ocs-hydrography/hydro_health pull request #5
Opened 2024-10-21 20:25 UTC by almccutc

@stephen-patterson-noaa I forgot to show you this earlier but I also added the function for downloading the sediment data to the download_hydrohealth_data script.

2024-10-22 15:33 UTC, stephen-patterson-noaa requested changes
I added a couple comments about recommended changes.  Otherwise looks good.

2025-02-26 19:05 UTC, stephen-patterson-noaa requested changes
Couple variables need fixed.

2025-02-26 19:05 UTC, stephen-patterson-noaa commented on src/hydro_health/engines/CreateSedimentLayerEngine.py
> +        file_path = INPUTS / "sediment_data" / f"{tile_number}_{field_name}_raster.tif"
Nice method for multiple uses in the code.

2025-02-27 15:28 UTC, almccutc commented on src/hydro_health/engines/CreateSedimentLayerEngine.py
> +        # but is actually fast in python
Makes sense. I removed this TODO, I decided to keep the clip

2025-02-27 16:13 UTC, almccutc commented on src/hydro_health/engines/CreateSedimentLayerEngine.py
> +        file_path = INPUTS / "sediment_data" / f"{tile_number}_{field_name}_raster.tif"
Yeah we can probably use convert_polys_to_raster for some of the other creation engines too

2025-02-27 16:14 UTC, almccutc commented on src/hydro_health/engines/CreateSedimentLayerEngine.py
> +        file_path = INPUTS / "sediment_data" / f"{tile_number}_{field_name}_raster.tif"
I added a way to extract tile_number from the tile_path

2025-02-27 16:39 UTC, almccutc commented on src/hydro_health/engines/CreateSedimentLayerEngine.py
> +        mask_gdf = gpd.read_file(tile_path)
I added it as self.tile_path for now. We need to consider how we are going to call the engine for each tile, like will it be for the larger tiles or the subgrids? I added a TODO in the code and made a backlog item on the jira board

2025-02-27 17:12 UTC, stephen-patterson-noaa approved these changes

2025-02-27 17:17 UTC, merged